Fix reader out of bounds
DataDog/golz4 pull request #9
Opened 2020-01-20 16:38 UTC by j-vizcaino

The first commit illustrates the issue (see CI).

When decompressing data, size of `dst` was not checked and the slice taken for writing turns into an out of bound panic.

The fix relies on a separate buffer to hold the decompressed that cannot be written right away.
The implementation is fairly straightforward: on Read() either consume from the internal buffer or decompress more data.

2020-01-20 19:40 UTC, HippoBaro requested changes
Nice catch! However, IMO passing a read buffer of the right size is the responsibility of the caller. 

For example on the write path we do https://github.com/DataDog/golz4/blob/4bea3580bba00ee002d357661401b249a5a6d970/lz4.go#L84-L86

Your solution adds pure overheads for callers that do the right thing.

2020-01-21 09:16 UTC, j-vizcaino commented
@HippoBaro Thanks for the review but I disagree with your point: there are lots of cases where the user has no control over the size of the buffer that is passed to the Read function. Just have a look at the unit test in https://github.com/DataDog/golz4/pull/9/commits/3a126b7edf22721078049e04fb1daa49ed20b0bd: bytes.Buffer reads from the LZ4 reader and we have no control over the size of the buffer.
Here is another real-world scenario that illustrates this: https://github.com/DataDog/dd-go/pull/17942/commits/1a38124a4c2a92f4d46c8b7bac18b14e6c878e33#diff-a48157fe8a7dcfeb8fa1bc89948fea81R17

Furthermore, I don't think the performance argument stands either, because, when the caller provides a buffer that is big enough, no pending slice gets created nor used. Unless I missed something, the current implementation does not apply extra data copied, compared to the previous one.

FWIW, I first tried to patch the Read function to make it return io.ErrShortBuffer, as I thought this would make the caller grow the buffer and try again but it turns out this is not correctly handled (by bytes.Buffer, at least).

2020-01-21 15:45 UTC, HippoBaro commented
I'm not very opinionated on the topic, but I would use a buffered reader on the client side in this case.

https://golang.org/pkg/bufio/#NewReaderSize

2020-01-21 16:00 UTC, j-vizcaino commented
While using a buffered reader would probably help, I do not think that having the reader know the max read size beforehand is a good pattern.
How is the reader supposed to know the max size a given inflate operation can return anyway?
And even if it did based on how the bytestream was written, it feels like coupling two components or apps for no obvious reason, making future changes harder than it should.

2020-01-21 16:14 UTC, HippoBaro commented
That's a fair point; my approach comes from using the lz4 library itself. It solves this problem by providing a function returning a buffer length to external users.

https://github.com/lz4/lz4/blob/c7ad96e299545330617e95eebc1369edd4e5fdf0/lib/lz4.h#L173-L182

I misread the code btw, you're not adding overhead; apologies.

2020-01-21 16:23 UTC, j-vizcaino commented
> That's a fair point; my approach comes from using the lz4 library itself. It solves this problem by providing a function returning a buffer length to external users.
> 
> https://github.com/lz4/lz4/blob/c7ad96e299545330617e95eebc1369edd4e5fdf0/lib/lz4.h#L173-L182

Thanks for the pointer but this function is only meant to be used when compressing (it is already provided by https://github.com/DataDog/golz4/blob/master/lz4.go#L50 FWIW).

This PR is about reads, not writes ;)

2020-01-21 16:33 UTC, HippoBaro commented
All good then; your code works and does the job. :shipit: !

2020-01-21 17:07 UTC, zzzzssss approved these changes
I think the fix gives the lz4 reader a more general usage, without letting the caller worrying about the size for the block size, so go ahead

2020-01-21 17:18 UTC, merged